server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/**
        - id: consumerModule
          uri: http://localhost:9090/
          predicates:
            - Path=/api1/v1/**
